/*******************************************************************************
 * Copyright 2010 Dieselpoint, Inc.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/
package org.openpipeline.pipeline.stage.opencalais;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.1
 * Tue May 05 12:59:21 CDT 2009
 * Generated source version: 2.2.1
 * 
 */
 
@WebService(targetNamespace = "http://clearforest.com/", name = "calaisSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface CalaisSoap {

    @WebResult(name = "EnlightenResult", targetNamespace = "http://clearforest.com/")
    @RequestWrapper(localName = "Enlighten", targetNamespace = "http://clearforest.com/", className = "com.clearforest.Enlighten")
    @ResponseWrapper(localName = "EnlightenResponse", targetNamespace = "http://clearforest.com/", className = "com.clearforest.EnlightenResponse")
    @WebMethod(operationName = "Enlighten", action = "http://clearforest.com/Enlighten")
    public java.lang.String enlighten(
        @WebParam(name = "licenseID", targetNamespace = "http://clearforest.com/")
        java.lang.String licenseID,
        @WebParam(name = "content", targetNamespace = "http://clearforest.com/")
        java.lang.String content,
        @WebParam(name = "paramsXML", targetNamespace = "http://clearforest.com/")
        java.lang.String paramsXML
    );
}
